# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
url: "https://ubc-lib-geo.github.io" # The base hostname & protocol for your site, e.g. http://example.com
baseurl: "/openindexmap-o-matic" # The subpath of your site, e.g. /blog
indexfolder: "/maps" # The subpath where index .md files are be stored
title: "UBC Library Map Set Viewer" # The name of your site, e.g. '[YOUR LIBRARY]'s Map Set Viewer'.
theme: minima


plugins:
  #- jekyll-feed
mapbox-access-token: "pk.eyJ1IjoidGhlaGVsbG9tYXJ0aWFuIiwiYSI6ImNsMDc1NXBuazF6bXczZXJzd2ZseXB4MDgifQ.gQNA94PswehVHrpv6cBBSw" # Replace with your own token - required to use Mapbox's vector tile servers.
mapbox-style: "mapbox://styles/mapbox/light-v11" 
header_pages:
 - about.md
