# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
url: "https://ubc-lib-geo.github.io" # The base hostname & protocol for your site, e.g. http://example.com
baseurl: "/openindexmap-o-matic" # The subpath of your site, e.g. /blog
indexfolder: "/maps" # The subpath where index .md files will be stored
title: "UBC Library Map Set Viewer" # The name of your site, e.g. '[YOUR LIBRARY]'s Topo Map Finder'.
theme: minima
plugins:
  - jekyll-feed
mapbox-access-token: "pk.eyJ1IjoiZWN0MTIzIiwiYSI6ImNranAwN2V5cjA0OGwyc3RjMG81YmY5dzAifQ.E1gXN2BWib0Z0pnS95iOtg" # Replace with your own token - required to use Mapbox's vector tile servers.
mapbox-style: "mapbox://styles/ect123/ck4ym048y4upi1cmzoq53immx" # Your preferred Mapbox style ID to be used for your basemap.